### ISSUE TITLE
업데이트 시 설정해 둔 자동 다운로드 리스트 등을 그대로 유지하는 방법이 있을까요?

### ISSUE THREAD

**Issue by the-xero** [banyazavi/tsharp#3]
반야자비님, tsharp을 너무 잘 쓰고 있습니다.

1. 최근 업데이트에서 궁금한 부분이 있어 이슈를 남깁니다.
watchtower가 tsharp을 자동 업데이트 시킨 것 같은데, 자동 다운로드나 폴더 리스트 등이 모두 날아갔습니다.
/root/data 와 /var/www/html/torr 을 나스의 docker/tsharp 폴더 내에 마운트 시켜둔 상태입니다.

설정 내용을 유지할 수 있는 방법이 따로 있을까요?

2. 설정탭의 시놀로지 로그인은 어떤 역할을 하나요?

**Comment by banyazavi** [comment]
1. torrssen2 db가 정상적으로 바인딩 되지 않은 상태로 보입니다. `/root/data`와 바인딩한 디렉토리에 `h2.mv.db` 파일이 정상적으로 존재하는지 확인하세요.
2. 다운로드 스테이션을 위한 DSM 접속 정보입니다. tsharp에서는 내장 트랜스미션을 사용하므로 다운로드 스테이션은 쓰지 않습니다.
