### ISSUE TITLE
트랜스미션 문제

### ISSUE THREAD

**Issue by raylee4204** [banyazavi/tsharp#6]
몇일 전부터인가 트랜스미션에서 토렌트 파일이 다운로드가 안되네요

"retrieving metadata"에서 더이상 업데이트가 안되는거 같아요
![Screen Shot 2022-06-10 at 3 30 18 PM](https://user-images.githubusercontent.com/2085389/173137149-a48e2b1c-bb0b-490e-bcca-746ea892e681.png)
.

**Comment by banyazavi** [comment]
마그넷에 이상이 있거나, 마그넷을 통해 전송을 시작할 수 없는 환경인 것 같습니다. 마그넷에 이상이 있는지 먼저 확인하시기 바랍니다.

**Comment by raylee4204** [comment]
마그넷 체크는 어떻게 해야하나요? RSS 피드에서 잡히는 토렌트 파일로 다운요청하는게 아닌가요?

**Comment by banyazavi** [comment]
맞습니다. RSS 피드의 동일 마그넷을 다른 토렌트 클라이언트에 다운 요청하여 정상 실행되는지 봐야 할 것 같습니다.
마그넷을 잘못 받아오는 것인지, 트랜스미션의 네트워크에 문제가 있는지 판단해야 합니다.

**Comment by raylee4204** [comment]
시놀로지 DS218+에 다커로 사용중입니다.

**Comment by banyazavi** [comment]
방화벽 설정을 의심해볼 만 합니다. 방화벽을 잠깐 해제하고 다시 테스트 해 보세요.
설치법은 어디에 쓰여 있는 내용을 참고하셨나요?
