### ISSUE TITLE
rss 사이트 질문드립니다. 

### ISSUE THREAD

**Issue by ncae95** [banyazavi/tsharp#7]
tsharp 만들어주신 덕분에 잘 사용하고 있습니다. 

요즘 tsharp 기본 사이트인 torrentsir에서 자주 ww82torrentsir 이런 식으로 userconfig.php가 바뀌는 경우가 있어 오는것 같습니다. 
$OLD_DOMAIN = 'torrentsir56.com';
$NEW_DOMAIN = 'ww.82torrentsir.com'; 
사이트가 터진 사이에 다른 광고 사이트로 사이트가 업데이트 되어버리는 것 같은데
3~4일 정도 두더라도 문제가 해결되지 않고 저 사이트(ww82?)에서 업데이트가 되지 않더군요. 
그래서 든 생각이 crontab으로 도커가 자동 재부팅이 되고, 재부팅이 될 때마다 OLD_DOMAIN + 1로 늘어나는것이 아니라 NEW_DOMAIN에서 +1씩으로 늘어나는 것 같던데 혹여 OLD_DOMAIN부터 + 1로 읽어올 수 있도록 설정하면 해결할 수 있지 않을까 해서 질문을 남겨봅니다. 
혹여 해당 설정을 메뉴에 넣거나 아니면 userconfig.php 수정으로 설정을 변경할 수 있을까요?

**Comment by banyazavi** [comment]
안녕하세요. 티샵의 rss 크롤러는 자체 제작한 것이 아닌, **It's torr!**라고 하는 다른 오픈 소스 프로젝트를 사용하고 있습니다.
https://github.com/grollcake-torr/torr

말씀하신 방법은 해당 프로젝트에 제안하여 주시기 바랍니다. 또는 `torr.php`를 수정하여 `OLD_DOMAIN` 갱신 방법을 직접 변경하실 수도 있습니다.

**Comment by ncae95** [comment]
아.. 제가 잘못 알고 괜히 귀찮게 했네요 ;; 
답변 감사합니다.!
