### ISSUE TITLE
텔레그램 메세지 전송 복수 관련

### ISSUE THREAD

**Issue by darkhowk** [banyazavi/tsharp#8]
현재 잘 쓰고 있습니다. 
다만 텔레그램 메세지 전송 복수시에 
id1,id2 입력하면  id1에만 테스트 문구와 다운로드시 알림이 갑니다.

id2에는 가지 않는데, 확인 한번 부탁드립니다.

**Comment by banyazavi** [comment]
말씀한 이슈는 [torrssen2](https://github.com/tarpha/torrssen2) 프로젝트에 문의하는 것이 좋아 보입니다.
첨부한 스크린샷은 개인정보가 포함되어 있어 삭제했습니다.

**Comment by darkhowk** [comment]
확인 감사합니다 해당 프로젝트에 다시 질문하겠습니다.
